steps:
  # 1. Install dependancy
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # 2. Update your repository using 'git pull'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'instance-20241121-093404'
      - '--zone'
      - 'us-central1-b'
      - '--command'
      - |
        git config --global --add safe.directory /home/logicallawbio/ZEROFIT_NodeJS_Server && \
        cd /home/logicallawbio/ZEROFIT_NodeJS_Server && git pull

  # 3. Restart your server using pm2
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'instance-20241121-093404'
      - '--zone'
      - 'us-central1-b'
      - '--command'
      - |
        cd /home/logicallawbio/ZEROFIT_NodeJS_Server && \
        npx pm2 reload all

# logsBucket
logsBucket: 'gs://678969298134-us-central1-blueprint-config' 